#!/usr/bin/env python3
"""Generate catalogue.json, INDEX.md, and the README table.

meta/ is the source of truth. All three outputs are generated
and must never be hand-edited. The README's table is a region
inside a hand-written file, marked by the comments in
README_BEGIN and README_END; everything outside them is left
exactly as it was.

    python3 tools/build_catalogue.gpt.py            # write
    python3 tools/build_catalogue.gpt.py --check    # compare

--check renders to memory and compares bytes against what is
committed. It never writes, so running the check cannot be
what makes the check pass.
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIST_KEYS = {"triggers", "aliases", "tested_agents", "clients"}
BOOL_KEYS = {"writes", "network", "executes"}
# Coerced to int so ordering is numeric. As strings, "10" sorts
# before "2", which would silently reshuffle the catalogue at the
# tenth skill.
INT_KEYS = {"order"}

MARKETPLACE = "trycopilotai"

# An entry with no `clients` predates the field and ships for
# Claude Code only. validate.gpt.py compares this same default
# against the manifests on disk, so it cannot quietly describe
# a plugin that actually carries Codex metadata.
DEFAULT_CLIENTS = ["claude-code"]
CLIENT_LABELS = {"claude-code": "Claude Code", "codex": "Codex"}

README = "README.md"
README_BEGIN = (
    "<!-- Generated by tools/build_catalogue.gpt.py. Do not edit. -->"
)
README_END = "<!-- End generated table. -->"


def parse(path: Path) -> dict:
    """Parse the small YAML subset meta/*.skill.yml uses."""
    out: dict = {}
    key = None
    for line in path.read_text().split("\n"):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith("  - ") and key in LIST_KEYS:
            out.setdefault(key, []).append(line[4:].strip())
            continue
        if line.startswith("  ") and key and not isinstance(out.get(key), list):
            out[key] = (str(out.get(key, "")) + " " + line.strip()).strip()
            continue
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if val in (">-", "|", "|-", ">"):
            out[key] = ""
        elif key in LIST_KEYS:
            out[key] = []
        elif key in BOOL_KEYS:
            # Leave anything that is not literally true or false
            # as a string, so validate.gpt.py reports it rather
            # than this silently reading it as false. A misspelled
            # flag used to render a command-running skill as
            # read-only, which is the one error the badge exists
            # to prevent.
            if val in ("true", "false"):
                out[key] = val == "true"
            else:
                out[key] = val
        elif key in INT_KEYS:
            # Same reasoning: a non-integer stays a string so the
            # validator reports it.
            out[key] = int(val) if val.lstrip("-").isdigit() else val
        else:
            out[key] = val
    return out


def order_key(skill: dict) -> tuple:
    """Sort by explicit order, then name.

    A skill with no usable `order` sorts after every skill that
    has one, alphabetically among its peers, so a forgotten key
    degrades to the old behaviour instead of crashing the build.
    `make validate` is what fails on the missing key.
    """
    raw = skill.get("order")
    name = skill.get("name", "")
    if isinstance(raw, int) and not isinstance(raw, bool):
        return (0, raw, name)
    return (1, 0, name)


def markdown_table(headers: tuple, rows: list) -> str:
    """Render a table with every column padded to one width.

    A one-row table can be written by hand. A table that grows
    a row per skill cannot, which is the reason this is
    generated at all.
    """
    widths = [len(h) for h in headers]
    for row in rows:
        if len(row) != len(headers):
            raise ValueError("Markdown table row has the wrong width")
        for index, cell in enumerate(row):
            widths[index] = max(widths[index], len(cell))

    def render_row(cells) -> str:
        return "| " + " | ".join(
            cell.ljust(widths[index]) for index, cell in enumerate(cells)
        ) + " |"

    lines = [render_row(headers), render_row(["-" * w for w in widths])]
    lines.extend(render_row(row) for row in rows)
    return "\n".join(lines)


def skill_label(s: dict) -> str:
    """The skill's name, linked only when the link resolves.

    A pending entry has no published upstream to point at yet.
    Linking one anyway would put a 404 in front of a reader as
    the marketplace's own evidence that the skill exists.
    """
    url = s.get("upstream", "")
    if url and not url.startswith("http"):
        url = "https://" + url
    name = f"`{s['name']}`"
    if s.get("status") == "published" and url:
        return f"[{name}]({url})"
    return name


def render() -> dict:
    """Build every output in memory. Writes nothing."""
    skills = [parse(p) for p in sorted((ROOT / "meta").glob("*.skill.yml"))]
    skills.sort(key=order_key)
    for s in skills:
        s.setdefault("clients", list(DEFAULT_CLIENTS))

    catalogue = json.dumps({"version": 1, "skills": skills}, indent=2) + "\n"

    index_rows = []
    readme_rows = []
    for s in skills:
        # `is True` on purpose. A malformed flag is a string here,
        # and a truthy string would print as a capability the
        # skill never declared.
        caps = [k for k in ("writes", "network", "executes") if s.get(k) is True]
        clients = [
            CLIENT_LABELS.get(c, c)
            for c in s.get("clients", [])
            if isinstance(c, str)
        ]
        label = skill_label(s)
        use = s.get("use", "").strip()
        index_rows.append((
            label,
            s.get("category", ""),
            s.get("status", ""),
            ", ".join(clients),
            ", ".join(caps) if caps else "read-only",
            use,
        ))
        readme_rows.append((label, ", ".join(clients), use))

    plural = "s" if len(skills) != 1 else ""
    index = (
        f"{README_BEGIN}\n\n"
        "# Skill index\n\n"
        f"{len(skills)} skill{plural} in the `{MARKETPLACE}` marketplace.\n\n"
        + markdown_table(
            ("Skill", "Category", "Status", "Clients", "Side effects",
             "What it does"),
            index_rows,
        )
        + "\n\nRegenerate with `make catalogue`.\n"
    )
    readme_table = markdown_table(
        ("Skill", "Clients", "What it does"), readme_rows
    )
    return {
        "catalogue.json": catalogue,
        "INDEX.md": index,
        "readme_table": readme_table,
        "count": len(skills),
    }


def readme_with_table(current: str, table: str) -> str:
    """Replace the marked region of README.md, keeping the rest."""
    begin = current.find(README_BEGIN)
    end = current.find(README_END)
    if begin < 0 or end < 0 or end < begin:
        raise SystemExit(
            f"{README} has no generated table region; expected "
            f"{README_BEGIN!r} and {README_END!r}"
        )
    return (
        current[:begin]
        + README_BEGIN
        + "\n\n"
        + table
        + "\n\n"
        + current[end:]
    )


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="compare against the committed output instead of writing",
    )
    args = ap.parse_args(argv)

    built = render()
    names = ("catalogue.json", "INDEX.md")

    readme_path = ROOT / README
    if not readme_path.exists():
        print(f"  {README} is missing")
        return 1
    readme_current = readme_path.read_text()
    readme_built = readme_with_table(readme_current, built["readme_table"])

    if args.check:
        stale = []
        for name in names:
            path = ROOT / name
            if not path.exists():
                stale.append(f"{name} is missing")
            elif path.read_text() != built[name]:
                stale.append(f"{name} differs from a fresh build")
        if readme_current != readme_built:
            stale.append(f"{README}'s generated table differs from a "
                         f"fresh build")
        if stale:
            for line in stale:
                print(f"  {line}")
            print("catalogue is stale; run 'make catalogue'")
            return 1
        print(f"OK    catalogue is current ({built['count']} skills)")
        return 0

    for name in names:
        (ROOT / name).write_text(built[name])
    readme_path.write_text(readme_built)
    print(
        f"wrote catalogue.json, INDEX.md, and the {README} table "
        f"({built['count']} skills)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
