#!/usr/bin/env python3
"""Generate catalogue.json and INDEX.md from meta/*.skill.yml.

meta/ is the source of truth. Both outputs are generated and
must never be hand-edited.

    python3 tools/build_catalogue.gpt.py            # write
    python3 tools/build_catalogue.gpt.py --check    # compare

--check renders to memory and compares bytes against what is
committed. It never writes, so running the check cannot be
what makes the check pass.
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIST_KEYS = {"triggers", "aliases", "tested_agents"}
BOOL_KEYS = {"writes", "network", "executes"}
# Coerced to int so ordering is numeric. As strings, "10" sorts
# before "2", which would silently reshuffle the catalogue at the
# tenth skill.
INT_KEYS = {"order"}

MARKETPLACE = "trycopilotai"


def parse(path: Path) -> dict:
    """Parse the small YAML subset meta/*.skill.yml uses."""
    out: dict = {}
    key = None
    for line in path.read_text().split("\n"):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith("  - ") and key in LIST_KEYS:
            out.setdefault(key, []).append(line[4:].strip())
            continue
        if line.startswith("  ") and key and not isinstance(out.get(key), list):
            out[key] = (str(out.get(key, "")) + " " + line.strip()).strip()
            continue
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if val in (">-", "|", "|-", ">"):
            out[key] = ""
        elif key in LIST_KEYS:
            out[key] = []
        elif key in BOOL_KEYS:
            # Leave anything that is not literally true or false
            # as a string, so validate.gpt.py reports it rather
            # than this silently reading it as false. A misspelled
            # flag used to render a command-running skill as
            # read-only, which is the one error the badge exists
            # to prevent.
            if val in ("true", "false"):
                out[key] = val == "true"
            else:
                out[key] = val
        elif key in INT_KEYS:
            # Same reasoning: a non-integer stays a string so the
            # validator reports it.
            out[key] = int(val) if val.lstrip("-").isdigit() else val
        else:
            out[key] = val
    return out


def order_key(skill: dict) -> tuple:
    """Sort by explicit order, then name.

    A skill with no usable `order` sorts after every skill that
    has one, alphabetically among its peers, so a forgotten key
    degrades to the old behaviour instead of crashing the build.
    `make validate` is what fails on the missing key.
    """
    raw = skill.get("order")
    name = skill.get("name", "")
    if isinstance(raw, int) and not isinstance(raw, bool):
        return (0, raw, name)
    return (1, 0, name)


def render() -> dict:
    """Build both outputs in memory. Writes nothing."""
    skills = [parse(p) for p in sorted((ROOT / "meta").glob("*.skill.yml"))]
    skills.sort(key=order_key)

    catalogue = json.dumps({"version": 1, "skills": skills}, indent=2) + "\n"

    rows = []
    for s in skills:
        url = s.get("upstream", "")
        if url and not url.startswith("http"):
            url = "https://" + url
        # `is True` on purpose. A malformed flag is a string here,
        # and a truthy string would print as a capability the
        # skill never declared.
        caps = [k for k in ("writes", "network", "executes") if s.get(k) is True]
        rows.append(
            f"| [`{s['name']}`]({url}) "
            f"| {s.get('category', '')} "
            f"| {s.get('status', '')} "
            f"| {', '.join(caps) if caps else 'read-only'} "
            f"| {s.get('use', '').strip()} |"
        )

    index = (
        "<!-- Generated by tools/build_catalogue.gpt.py. Do not edit. -->\n\n"
        "# Skill index\n\n"
        f"{len(skills)} skill{'s' if len(skills) != 1 else ''} in the "
        f"`{MARKETPLACE}` marketplace.\n\n"
        "| Skill | Category | Status | Side effects | What it does |\n"
        "| ----- | -------- | ------ | ------------ | ------------ |\n"
        + "\n".join(rows)
        + "\n\nRegenerate with `make catalogue`.\n"
    )
    return {"catalogue.json": catalogue, "INDEX.md": index, "count": len(skills)}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check",
        action="store_true",
        help="compare against the committed output instead of writing",
    )
    args = ap.parse_args(argv)

    built = render()
    names = ("catalogue.json", "INDEX.md")

    if args.check:
        stale = []
        for name in names:
            path = ROOT / name
            if not path.exists():
                stale.append(f"{name} is missing")
            elif path.read_text() != built[name]:
                stale.append(f"{name} differs from a fresh build")
        if stale:
            for line in stale:
                print(f"  {line}")
            print("catalogue is stale; run 'make catalogue'")
            return 1
        print(f"OK    catalogue is current ({built['count']} skills)")
        return 0

    for name in names:
        (ROOT / name).write_text(built[name])
    print(f"wrote catalogue.json and INDEX.md ({built['count']} skills)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
