#!/usr/bin/env python3
"""Generate catalogue.json and INDEX.md from meta/*.skill.yml.

meta/ is the source of truth. Both outputs are generated and
must never be hand-edited. `make catalogue-check` fails when
the committed output does not match a fresh build.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LIST_KEYS = {"triggers", "aliases", "tested_agents"}
BOOL_KEYS = {"writes", "network", "executes"}
# Coerced to int so ordering is numeric. As strings, "10" sorts
# before "2", which would silently reshuffle the catalogue at the
# tenth skill.
INT_KEYS = {"order"}


def parse(path: Path) -> dict:
    """Parse the small YAML subset meta/*.skill.yml uses."""
    out: dict = {}
    key = None
    for line in path.read_text().split("\n"):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line.startswith("  - ") and key in LIST_KEYS:
            out.setdefault(key, []).append(line[4:].strip())
            continue
        if line.startswith("  ") and key and not isinstance(out.get(key), list):
            out[key] = (str(out.get(key, "")) + " " + line.strip()).strip()
            continue
        m = re.match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        if not m:
            continue
        key, val = m.group(1), m.group(2).strip()
        if val in (">-", "|", "|-", ">"):
            out[key] = ""
        elif key in LIST_KEYS:
            out[key] = []
        elif key in BOOL_KEYS:
            out[key] = val.lower() == "true"
        elif key in INT_KEYS:
            # Leave a non-integer as a string so validate.gpt.py
            # reports it rather than this silently accepting it.
            out[key] = int(val) if val.lstrip("-").isdigit() else val
        else:
            out[key] = val
    return out


def order_key(skill: dict) -> tuple:
    """Sort by explicit order, then name.

    A skill with no usable `order` sorts after every skill that
    has one, alphabetically among its peers, so a forgotten key
    degrades to the old behaviour instead of crashing the build.
    `make validate` is what fails on the missing key.
    """
    raw = skill.get("order")
    name = skill.get("name", "")
    if isinstance(raw, int) and not isinstance(raw, bool):
        return (0, raw, name)
    return (1, 0, name)


def main() -> int:
    skills = [parse(p) for p in sorted((ROOT / "meta").glob("*.skill.yml"))]
    skills.sort(key=order_key)

    (ROOT / "catalogue.json").write_text(
        json.dumps({"version": 1, "skills": skills}, indent=2) + "\n"
    )

    rows = []
    for s in skills:
        url = s.get("upstream", "")
        if url and not url.startswith("http"):
            url = "https://" + url
        caps = [k for k in ("writes", "network", "executes") if s.get(k)]
        rows.append(
            f"| [`{s['name']}`]({url}) "
            f"| {s.get('category', '')} "
            f"| {s.get('status', '')} "
            f"| {', '.join(caps) if caps else 'read-only'} "
            f"| {s.get('use', '').strip()} |"
        )

    (ROOT / "INDEX.md").write_text(
        "<!-- Generated by tools/build_catalogue.gpt.py. Do not edit. -->\n\n"
        "# Skill index\n\n"
        f"{len(skills)} skill{'s' if len(skills) != 1 else ''} in the "
        "`trycopilotai` marketplace.\n\n"
        "| Skill | Category | Status | Side effects | What it does |\n"
        "| ----- | -------- | ------ | ------------ | ------------ |\n"
        + "\n".join(rows)
        + "\n\nRegenerate with `make catalogue`.\n"
    )
    print(f"wrote catalogue.json and INDEX.md ({len(skills)} skills)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
